# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HYD_WpFcgwo0VczBFlwkmMqmLeJ6wt-j
"""

import pandas as pd
import numpy as np
#!pip install tensorflow
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import  Embedding, Dense, Dropout, GlobalAveragePooling2D,concatenate,Conv2D,MaxPooling2D,GlobalAveragePooling1D
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
#!pip install opencv-python
import cv2
import os
from tensorflow.keras.utils import image_dataset_from_directory
from tensorflow.keras.applications import MobileNetV2
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Concatenate
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, Dense, Dropout, GlobalAveragePooling1D
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score
import seaborn as sns

import kagglehub
path = kagglehub.dataset_download("nithin1729s/multimodal-real-fake-job-posting-prediction")

df=pd.read_csv(path+"/fake_job_postings.csv")

os.listdir(path)

df.head()

df.shape

df["description"] = df["description"].fillna("")
df["requirements"] = df["requirements"].fillna("")
df["title"] = df["title"].fillna("")

df["text"] = (
    df["title"] + " " +
    df["description"] + " " +
    df["requirements"]
)

def get_image_path(row):

    label = row['fraudulent']
    job_id = row['job_id']

    return f"{path}/images/{label}/{job_id}.png"


df['image_path'] = df.apply(get_image_path, axis=1)

df['image_exists'] = df['image_path'].apply(os.path.exists)
df = df[df['image_exists'] == True]

vocab_size = 10000
max_len = 200

tokenizer = Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(df["text"])
sequences = tokenizer.texts_to_sequences(df["text"])
X_text_all = pad_sequences(
    sequences,
    maxlen=max_len,
    padding='post'
)

IMG_SIZE = 128

images = []

for img_path in df['image_path']:

    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = cv2.resize(img, (IMG_SIZE, IMG_SIZE))

    images.append(img)

X_image_all = np.array(images) / 255.0

y = df['fraudulent'].values

X_text_train, X_text_test, X_img_train, X_img_test, y_train, y_test = train_test_split(
    X_text_all, X_image_all,  y, test_size=0.2, random_state=42, stratify=y)

image_input = Input(shape=(128,128,3))

base_model = MobileNetV2(
    weights='imagenet',
    include_top=False,
    input_tensor=image_input
)

base_model.trainable = False

x = base_model.output
x=Conv2D( 32,(3,3),activation="relu",padding="same",name="conv_1")(x)
x=MaxPooling2D((2,2),name="maxPool_1")(x)
x=Conv2D( 64,(3,3),activation="relu",padding="same",name="conv_2")(x)
x=MaxPooling2D((2,2),name="maxPool_2")(x)
x = GlobalAveragePooling2D()(x)
img_features = Dense(64, activation='relu')(x)

df['image_exists'] = df['image_path'].apply(os.path.exists)
df['image_exists'].value_counts()

text_input = Input(shape=(max_len,))
text_features = Embedding(input_dim=vocab_size, output_dim=128)(text_input)
text_features = GlobalAveragePooling1D()(text_features)
text_features = Dense(64, activation='relu')(text_features)
text_features = Dropout(0.3)(text_features)

combined = Concatenate()([img_features,text_features])

x = Dense( 64,activation='relu')(combined)
x = Dropout(0.3)(x)
output = Dense(1,activation='sigmoid')(x)

model = Model( inputs=[image_input, text_input],outputs=output)

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
er=tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=3,restore_best_weights=True)

model.summary()

history = model.fit([X_img_train, X_text_train], y_train,validation_data=([X_img_test, X_text_test], y_test ),epochs=100,batch_size=32,callbacks=[er])

loss, accuracy = model.evaluate( [X_img_test, X_text_test],  y_test)
print("Accuracy:", accuracy)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.savefig('accuracy_multimodal.png')
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'])
plt.savefig('loss.png')
plt.show()

y_pred = model.predict([X_img_test, X_text_test])
y_pred = (y_pred > 0.5).astype(int)
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.savefig('confusion_matrix.png')
plt.show()

print(classification_report(y_test, y_pred))

model.save("fake_job_multimodal_model.keras")

import pickle

with open("tokenizer.pkl", "wb") as f:
    pickle.dump(tokenizer, f)

from google.colab import files
files.download("fake_job_multimodal_model.keras")